### ISSUE TITLE
Background Color Feedback and Preset request for AVHS410

### ISSUE THREAD

**Issue by samuraitheta** [bitfocus/companion-module-panasonic-avhs#3]
Hello!

I recently started using the AV-HS410 module and I see that we have a dynamic variable for each bus, but I was wondering if we could use that information to change the background color on the button for the XPT that is selected. For example, in the OBS module... the button on companion for the scene that is selected in OBS will have a red background and white text... while the rest are standard. 

Is it possible to use the string for the XPT that is active for feedback to the button colors? Also, would it be possible to have presets for this? ie: Bus A XPT 1 - XPT 12, ETC?

I don't mind helping with this, but I'm not sure how. I have some scripting experience. 

Thanks!
Matthew

**Comment by McHauge** [comment]
@samuraitheta That's deffently something that should be possible, I think there is an internal feedback that reacts to variables, at least in the newer beta builds. As for a feedback inside the module itself, that's just because I haven't had the time for it, as it was just variables i needed for a specific use case i had.

**Comment by samuraitheta** [comment]
Copy that! I am hoping to use this module more, and I would love to extend the functionality. Let me know if I can help!

**Comment by McHauge** [comment]
@samuraitheta JUst took a look at it, and if you could take a look at a developer build for me that would be great :)

I have uploaded a build for Windows on my Companion-Dev OneDrive, here is the link for the build: [OneDrive (Download)](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

**Comment by McHauge** [comment]
@samuraitheta I have pushed the feedbacks, but I still need to test them before they get included in the beta builds :)

**Comment by McHauge** [comment]
@samuraitheta Hi, I just finished testing my changes, and qued it for inclusion into the core, you should be able to download a beta version 2.2.0 build of companion later today or tomorrow with the additions. I'll cost this, for now, feel free to reopen this.
