### ISSUE TITLE
Dont register uncaughtException handler

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-panasonic-avhs#4]
https://github.com/bitfocus/companion-module-panasonic-avhs/blob/b565dfe1d28845bd43338d59a65a2b289a6e20f3/index.js#L556

The module should not be doing this. This is a global event handler, and should not be used to handle an event from a specific socket. Instead you should be using the `.on('error', function(){` for the socket you want to handle the error for.

This will be leaking a reference to the instance each time `listenMulticast()` is called, and will be causing companion to exit on error instead of the correct error handling

**Comment by McHauge** [comment]
will change this over to the same setup as with the PTZ's

**Comment by McHauge** [comment]
think that should do it, but i still need to test it, so I'll report back at a later point

**Comment by McHauge** [comment]
closing this as it's now fixed
