### ISSUE TITLE
AUTO command not working on AV-HS410

### ISSUE THREAD

**Issue by AllanPill** [bitfocus/companion-module-panasonic-avhs#8]
I can't seem to get AUTO commands to execute on the HS410 mixer, everything else works well (tally feedback, CUT, crosspoint switching). 
Running Companion 2.4.1.

Other than that a great module! It has enabled us to use Companion and Stream Decks with Panasonic PTZ cameras while the 410 AUX-es act as on-demand PTZ operator preview outputs.

**Comment by josephdadams** [comment]
This is fixed - I added a new action called "Auto (2)" which sends the correct command specifically for the HS410.
